[theme]
# The primary color for interactive elements
primaryColor="#2E86C1"

# The background color for the main content area
backgroundColor="#F7F9F9"

# The background color for the sidebar
secondaryBackgroundColor="#EBF5FB"

# The color for text
textColor="#0B2F44"

# The font family
font="sans serif"